# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- release/*

pr:
 - main
 - release/*

pool:
  vmImage: ubuntu-latest
  

stages:

  - stage: BuildWin
    displayName: Build for Windows
    jobs:
    - job: BuildAJob
      steps:
      - script: echo Building!
      - script: npm install
      - script: npm install @salesforce/cli --global
      - script: sf --version
  - stage: BuildMac
    displayName: Build for Mac
    dependsOn: []
    jobs:
    - job: BuildBJob
      steps:
      - script: echo Building!
      - script: npm install
      - script: npm install @salesforce/cli --global
      - script: sf --version

  - stage: Build
    dependsOn: []
    jobs:
    - job: BuildJob
      steps:
      - script: echo Building!
      - script: npm install
      - script: npm install @salesforce/cli --global
      - script: sf --version

  - stage: Test
    jobs:
    - job: TestOnWindows
      steps:
      - script: echo Testing on Windows!
    - job: TestOnLinux
      steps:
      - script: echo Testing on Linux!
      
  - stage: Deploy
    jobs:
    - job: Deploy
      steps:
      - script: echo Deploying the code!
